### ISSUE TITLE
Composer.json

### ISSUE THREAD

**Issue by chellem** [Nylle/PHP-AutoMapper#2]
Hi,

Is it possible to add a composer.json and add the library to packagist?

Regards

**Comment by Nylle** [comment]
Thanks for your interest in PHP-AutoMapper. Unfortunately I don't do PHP anymore. But you are very welcome to make a pull-request and get things done. Cheers

**Comment by Nylle** [comment]
Hi chellem, composer integration has been added with [Pull Request #5](https://github.com/Nylle/PHP-AutoMapper/pull/5) by [kristoftorfs](https://github.com/Nylle/PHP-AutoMapper/issues?q=is%3Apr+author%3Akristoftorfs).
