### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by Jelle-S** [Nylle/PHP-AutoMapper#4]
Could this library be made available through composer?

**Comment by Nylle** [comment]
Hi Jelle, if you want to add composer support, I see no reason why not. You are very welcome to go ahead and make a pull request.

**Comment by Nylle** [comment]
Hi Jelle, composer integration has been added with [Pull Request #5](https://github.com/Nylle/PHP-AutoMapper/pull/5) by [kristoftorfs](https://github.com/Nylle/PHP-AutoMapper/issues?q=is%3Apr+author%3Akristoftorfs).
